name: OWASP Dependency-Check

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Run OWASP Dependency-Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'TransChile'
        path: '.'
        format: 'HTML,JSON'
        out: './reports'
        
    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-html-report
        path: reports/dependency-check-report.html
        
    - name: Upload JSON report
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-json-report
        path: reports/dependency-check-report.json
    
    - name: Set JAVA_HOME
      run: |
        echo "JAVA_HOME=${{ env.JAVA_HOME_11_X64 }}" >> $GITHUB_ENV
        echo "${{ env.JAVA_HOME_11_X64 }}/bin" >> $GITHUB_PATH