name: TransChile Node.js Dependency Security Scan

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  schedule:
    - cron: '0 0 * * *'

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          node_modules
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}-
          ${{ runner.os }}-node-

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run OWASP Dependency-Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'TransChile (Node ${{ matrix.node-version }})'
        path: '.'
        format: 'HTML,JSON'
        out: './security-reports/${{ matrix.node-version }}'
        args: >-
          --disableAssembly
          --scan ./package-lock.json
          --scan ./node_modules/
          --failOnCVSS 7
          --noupdate

    - name: Run npm audit
      run: npm audit --audit-level=high || echo "npm audit found vulnerabilities"

    - name: Upload Dependency-Check reports
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-reports-node-${{ matrix.node-version }}
        path: |
          security-reports/${{ matrix.node-version }}/dependency-check-report.html
          security-reports/${{ matrix.node-version }}/dependency-check-report.json

    - name: Upload npm audit report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: npm-audit-report-node-${{ matrix.node-version }}
        path: npm-audit-report.html
      continue-on-error: true