name: TransChile Node.js Dependency Security Scan

on:
  push:
    branches: [ main, dev]
  pull_request:
    branches: [ main, dev]
  schedule:
    - cron: '0 0 * * *'

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x] # Nombre más descriptivo

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run OWASP Dependency-Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'TransChile (Node ${{ matrix.node-version }})'
        path: '.'
        format: 'HTML,JSON'
        out: './security-reports/${{ matrix.node-version }}'
        args: >-
          --disableAssembly
          --scan ./package-lock.json
          --scan ./node_modules/
          --enableNpmAudit
          --failOnCVSS 7

    - name: Upload reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports-node-${{ matrix.node-version }}
        path: |
          security-reports/${{ matrix.node-version }}/dependency-check-report.html
          security-reports/${{ matrix.node-version }}/dependency-check-report.json